name: Greetings

on: [pull_request_target, issues]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - uses: actions/first-interaction@1dbfe1ba5525b8257e1f259b09745bee346d62d8 # v1.2.0
      with:
        repo-token: ${{ secrets.GREETINGS }}
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue!'
        pr-message: 'Hello @${{ github.actor }} , thank you submitting a pull request!'
 