name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GREETINGS }}
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue!'
        pr-message: 'Hello @${{ github.actor }} , thank you submitting a pull request!'
 