name: Greetings

on: [pull_request_target, issues]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - uses: actions/first-interaction@1d8459ca65b335265f1285568221e229d45a995e # v1.1.1
      with:
        repo-token: ${{ secrets.GREETINGS }}
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue!'
        pr-message: 'Hello @${{ github.actor }} , thank you submitting a pull request!'
 